spring :
  data :
    mongodb :
      host : localhost
      port : 27017
      database : ezipflix
      collections :
        video-conversions : video_conversions
conversion:
  messaging :
    rabbitmq :
      conversion-exchange: video-conversion-exchange
      conversion-queue: video-conversion-queue

rabbitmq-server:
  server: localhost
  port: 5672
  credentials:
    vhost: ezip         # sudo rabbitmqctl add_vhost ezip
                        # sudo rabbitmqctl set_permissions -p ezip ezip ".*" ".*" ".*"
    username: ezip      # sudo rabbitmqctl add_user ezip pize
    password: pize

